version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=infinitesounduser
      - POSTGRES_PASSWORD=infinitesoundpassword
      - POSTGRES_DB=infinitesound
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
